=== bengtmartensson/IrpTransmogrifier/src/main/schemas/irp-protocols.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet href="xsd.xsl" type="text/xsl"?>
<!-- Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  This file is offered as-is,
     without any warranty.
-->
<xs:schema targetNamespace="http://www.harctoolbox.org/irp-protocols"
           xmlns="http://www.harctoolbox.org/irp-protocols"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xml="http://www.w3.org/XML/1998/namespace"
           xmlns:html="http://www.w3.org/1999/xhtml"
           xmlns:xi="http://www.w3.org/2001/XInclude"
           elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:annotation>
        <xs:documentation>
            <html:div>
                The Girr format
                is documented at <html:a href="http://www.harctoolbox.org/Girr.html">www.harctoolbox.org/Girr.html</html:a>
            </html:div>
        </xs:documentation>
    </xs:annotation>

    <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>
    <xs:import namespace="http://www.w3.org/1999/xhtml" schemaLocation="http://www.w3.org/2002/08/xhtml/xhtml1-strict.xsd"/>
    <xs:import namespace="http://www.w3.org/2001/XInclude" schemaLocation="https://www.w3.org/2001/XInclude/XInclude.xsd"/>

    <xs:element name="protocols">
        <xs:complexType>
            <xs:annotation>
                <xs:documentation>The collection of protocols.
                </xs:documentation>
            </xs:annotation>
            <xs:sequence>
                <xs:element ref="adminData" minOccurs="0"/>
                <xs:choice maxOccurs="unbounded">
                    <xs:element ref="xi:include"/>
                    <xs:element ref="protocol"/>
                </xs:choice>
            </xs:sequence>
            <xs:attributeGroup ref="version"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="protocol">
        <xs:complexType>
            <xs:annotation>
                <xs:documentation>One protocol in IRP form.</xs:documentation>
            </xs:annotation>
            <xs:sequence maxOccurs="unbounded">
                <xs:choice>
                    <xs:element ref="irp"/>
                    <xs:element ref="documentation"/>
                    <xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
                </xs:choice>
            </xs:sequence>
            <xs:attributeGroup ref="name"/>
            <xs:attributeGroup ref="c-name"/>
            <xs:attributeGroup ref="usable"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="irp">
        <xs:complexType mixed="true"/>
    </xs:element>

    <xs:element name="documentation">
        <xs:complexType mixed="true">
            <xs:annotation>
                <xs:documentation>Textual notes, possibly using formatting in HTML.</xs:documentation>
            </xs:annotation>
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
            </xs:sequence>
            <xs:attribute ref="xml:lang" default="en"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="parameter">
        <xs:complexType mixed="true">
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:attributeGroup name="version">
        <xs:attribute name="version" type="xs:string">
            <xs:annotation>
                <xs:documentation>Version of the document.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:attributeGroup>

    <xs:attributeGroup name="name">
        <xs:attribute name="name" type="xs:string">
            <xs:annotation>
                <xs:documentation>Name of the protocol.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:attributeGroup>

    <xs:attributeGroup name="c-name">
        <xs:attribute name="c-name" type="xs:string">
            <xs:annotation>
                <xs:documentation>Name of the protocol, as used in code.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:attributeGroup>

    <xs:attributeGroup name="usable">
        <xs:attribute name="usable" type="xs:boolean">
            <xs:annotation>
                <xs:documentation>Setting this to false disables the protocol.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:attributeGroup>

    <xs:element name="adminData">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="creationData" minOccurs="0"/>
                <xs:element ref="versioningData" minOccurs="0"/>
                <xs:element ref="notes" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueLanguagesInNotesAdminData">
            <xs:selector xpath="notes"/>
            <xs:field xpath="@xml:lang"/>
        </xs:unique>
    </xs:element>

    <xs:element name="creationData">
        <xs:annotation>
            <xs:documentation>Describes how, from what, and by whom the document was created.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:attribute name="creatingUser" type="xs:string" use="optional">
                <xs:annotation>
                    <xs:documentation>Name of creating user</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="source" type="xs:string" use="optional">
                <xs:annotation>
                    <xs:documentation>Source of the information, for example, another document that was converted to the present one.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="creationDate" type="xs:string" use="optional">
                <xs:annotation>
                    <xs:documentation>Date of creation, or last modification.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="tool" type="xs:string" use="optional">
                <xs:annotation>
                    <xs:documentation>Name of creating tool.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="toolVersion" type="xs:string" use="optional">
                <xs:annotation>
                    <xs:documentation>Version of creating tool.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="tool2" type="xs:string" use="optional">
                <xs:annotation>
                    <xs:documentation>Name of secondary creating tool, if applicable.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="tool2Version" type="xs:string" use="optional">
            <xs:annotation>
                    <xs:documentation>Version of creating tool.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="versioningData">
        <xs:annotation>
            <xs:documentation>Versioning data; semanics is still to be determined.</xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="true">
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="notes">
        <xs:annotation>
            <xs:documentation>Textual notes, possibly using formatting in HTML.</xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
            </xs:sequence>
            <xs:attribute ref="xml:lang" default="en"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== bengtmartensson/IrpTransmogrifier/contributed/irp-protocols/applev2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- By Lyndel McGee -->
<irp:protocols xmlns="http://www.w3.org/1999/xhtml"
               xmlns:rm="https://sourceforge.net/projects/controlremote/files/RemoteMaster"
               xmlns:xi="http://www.w3.org/2001/XInclude"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               version="2024-10-29"
               xsi:schemaLocation="http://www.harctoolbox.org/irp-protocols http://www.harctoolbox.org/schemas/irp-protocols.xsd"
               xmlns:irp="http://www.harctoolbox.org/irp-protocols">
  <irp:protocol c-name="AppleV2" name="AppleV2">
        <!-- TODO Need better uei-executor specification -->
        <irp:parameter name="uei-executor">01E0{S=135,E=PairID}[D?0,E|||D?1,S,D?2,D?3;F,??,0]</irp:parameter>
        <irp:parameter name="prefer-over">NEC1-f16</irp:parameter>
        <irp:parameter name="prefer-over">NEC2-f16</irp:parameter>
        <irp:parameter name="prefer-over">NEC1</irp:parameter>
        <irp:parameter name="prefer-over">NEC-Shirriff-32</irp:parameter>
        <irp:parameter name="prefer-over">Apple</irp:parameter>
        <irp:irp><![CDATA[
                          {38.4k,564}<1,-1|1,-3>(16,-8,D:5,S:11,C:1,F:7,PairID:8,1,^108m,(16,-4,1,^108m)*)
                          {C=1-(#D+#F+#S+#PairID)%2,S=1087}
                          [D:0..31=14,F:0..127,PairID:0..255]
                ]]></irp:irp>
        <irp:documentation>Adapted from <a href="https://en.m.wikipedia.org/wiki/Apple_Remote#Technical_details">Wiki</a>.
        16 bits formatted as follows: device(5 bits) (aka Command Page); subdevice(11 bits):always 0x43F (aka Vendor 1087 decimal);
        checksum(1bit aka Odd Parity); function(7bits aka Function);
        PairID(8bits aka Device ID). C=1 if the number of 1 bits in the fields D, S, F,and PairID is even.
        Apple uses the same framing as <a href="#NEC1">NEC1</a>, where D is the command page.
        Specify D=14, or D=5 in normal use or specify D=0 for pairing (not recommended).
        S=1087</irp:documentation>
    </irp:protocol>
</irp:protocols>

=== bengtmartensson/IrpTransmogrifier/contributed/irp-protocols/apple_wiki.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Initiated by Lyndel McGee -->
<irp:protocols xmlns="http://www.w3.org/1999/xhtml"
               xmlns:rm="https://sourceforge.net/projects/controlremote/files/RemoteMaster"
               xmlns:xi="http://www.w3.org/2001/XInclude"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               version="2024-10-29"
               xsi:schemaLocation="http://www.harctoolbox.org/irp-protocols http://www.harctoolbox.org/schemas/irp-protocols.xsd"
               xmlns:irp="http://www.harctoolbox.org/irp-protocols">

    <irp:protocol name="Apple_wiki">
        <irp:irp>
            <![CDATA[{38.4k,564}<1,-1|1,-3>(16,-8,P:5,Vendor:11,C:1,F:7,D:8,1,^108m,(16,-4,1,^108m)*){Vendor=0x43f,C=1-(#P+#Vendor+#F+#D)%2}[P:0..31,F:0..127,D:0..255]]]>
        </irp:irp>
        <irp:documentation xml:space="preserve">This version of the  Apple protocol follows <a href="https://en.wikipedia.org/wiki/Apple_Remote">this wiki page</a>.</irp:documentation>
        <!--irp:parameter name="uei-executor">01E0{S=135,E=PairID}[D?0,E|||D?1,S,D?2,D?3;F,??,0]</irp:parameter-->
        <irp:parameter name="prefer-over">Apple</irp:parameter>
        <irp:parameter name="prefer-over">NEC1-f16</irp:parameter>
        <irp:parameter name="prefer-over">NEC2-f16</irp:parameter>
        <irp:parameter name="prefer-over">NEC1</irp:parameter>
        <irp:parameter name="prefer-over">NEC-Shirriff-32</irp:parameter>
    </irp:protocol>

</irp:protocols>

=== bengtmartensson/IrpTransmogrifier/src/test/resources/IrpProtocols-test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="IrpProtocols2html.xsl"?>
<irp:protocols xmlns="http://www.w3.org/1999/xhtml"
               xmlns:xi="http://www.w3.org/2001/XInclude"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               version="covfefe"
               xsi:schemaLocation="http://www.harctoolbox.org/irp-protocols http://www.harctoolbox.org/schemas/irp-protocols.xsd"
               xmlns:irp="http://www.harctoolbox.org/irp-protocols">

    <!-- No xi:fallback element: fatal error if xinclude fails -->
    <xi:include href="extra-protocol.xml" xpointer="element(/1/2)"/>

    <!-- Test of the fallback mechanism -->
    <xi:include href="no-such-file">
        <xi:fallback>
            <irp:protocol name="covid-19">
                <irp:irp>
            <![CDATA[{38.4k,564}<1,-1|1,-3>(16,-8,D:8,S:8,F:8,~F:8,1,^108m,(16,-4,1,^108m)*)[D:0..255,S:0..255=255-D,F:0..255]]]>
                </irp:irp>
                <irp:documentation>Lorem Ipsum</irp:documentation>
            </irp:protocol>
        </xi:fallback>
    </xi:include>

    <!-- remove this protocol -->
    <irp:protocol name="neC2"/>

    <!-- modify the NEC1 protocol -->
    <irp:protocol name="NEC1">

        <!-- add this -->
        <irp:parameter name="foo">bar</irp:parameter>
        <irp:parameter name="alt_name">NECrophile</irp:parameter>

        <!-- overwrite this -->
        <irp:documentation>Nec1 new doc</irp:documentation>

        <!-- add this -->
        <irp:parameter name="prefer-over">foobar</irp:parameter>

        <!-- Should NOT be added, since already there -->
        <irp:parameter name="prefer-over">Pioneer</irp:parameter>

    </irp:protocol>   <!-- modify the NEC1 protocol -->

    <irp:protocol name="NEC1-f16">

        <!-- add this -->
        <irp:documentation>Lorem Ipsum</irp:documentation>
    </irp:protocol>

    <!-- add this protocol -->
    <irp:protocol name="foobar">
        <irp:irp>
            <![CDATA[{38.4k,564}<1,-1|1,-3>(16,-8,D:8,S:8,F:8,~F:8,1,^108m,(16,-4,1,^108m)*)[D:0..255,S:0..255=255-D,F:0..255]]]>
        </irp:irp>
        <irp:documentation>Lorem Ipsum</irp:documentation>
    </irp:protocol>

    <!-- Remove all text properties with a certain name from a protocol -->
    <irp:protocol name="nec1">
        <irp:parameter name="uei-executor"/>
    </irp:protocol>

    <!-- Remove all xml properties with a certain name from a protocol -->
    <irp:protocol name="amino">
        <irp:parameter name="uei-executor" type="xml"/>
    </irp:protocol>

    <!-- nuke documentation -->
    <irp:protocol name="amino">
        <irp:documentation/>
    </irp:protocol>

    <!-- test that usable="false" works -->
    <irp:protocol name="covfefe" usable="false">
        <irp:irp>
            <![CDATA[{38.4k,564}<1,-1|1,-3>(16,-8,D:8,S:8,F:8,~F:8,1,^108m,(16,-4,1,^108m)*)[D:0..255,S:0..255=255-D,F:0..255]]]>
        </irp:irp>
        <irp:documentation>Lorem Ipsum</irp:documentation>
    </irp:protocol>

    <!-- Testing that both removal and addition of parameter values work together -->
    <irp:protocol name="Aiwa">
        <irp:parameter name="uei-executor">xxxxx</irp:parameter>
        <irp:parameter name="uei-executor"/> <!-- nukes everything up until now -->
        <irp:parameter name="uei-executor">9999[S;D,F]</irp:parameter>
    </irp:protocol>

</irp:protocols>
